version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns:
          - "@actions/*"
      typescript-build-tools:
        patterns:
          - "typescript"
          - "ts-jest"
          - "@tsconfig/node22"
          - "tsx"
      linting-tools:
        patterns:
          - "eslint"
          - "@sap/eslint-config"
          - "prettier"
      testing-frameworks:
        patterns:
          - "jest"
          - "@jest/globals"
          - "@types/jest"

  # Dockerfile-Dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "node"
