name: "Release Creator and Changelog Updater"
description: >
  Extracts the latest version from package.json and updates changelog.md.
  Creates a release with information from the changelog.
  Prepares changelog.md for the next run by adding a new 'unreleased' section.
  Dynamically lists Git commits since the last release and adds contributors.

inputs:
  github-token:
    required: false
    description: "GitHub Token for authentication."
    default: ${{ github.token }}
  dry-run:
    required: false
    description: "Enable dry-run mode (does not actually create a release)"
    default: "false"
  release-draft:
    description: "Mark release as draft."
    required: false
    default: false
  release-prerelease:
    description: "Mark release as prerelease."
    required: false
    default: false
  release-title-prefix:
    description: "Prefix for release title."
    required: false
    default: ""
  tag-template:
    description: "Custom template for tag naming (e.g., 'ms/<version>'). If empty, auto-detection is used."
    required: false
    default: "v<version>"
  fallback-version:
    description: "Fallback version if package.json has no version."
    required: false
    default: ""
  changelog-file-path:
    description: "Path to the changelog file."
    required: false
    default: "CHANGELOG.md"

runs:
  using: "docker"
  image: "Dockerfile"
