name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: release
        uses: ./
        with:
          tag-template: "v<version>"
          changelog-file-path: "CHANGELOG.md"
          ci-workflows: "auto"

      - name: Print release URL
        if: steps.release.outputs.release-url != ''
        run: echo "Released at ${{ steps.release.outputs.release-url }}"
